Add LogTypes.cc to the rccl OSS CMake src list (#3722)
Summary:

D115616289 split the Folly-free log types out into
comms/utils/logger/LogTypes.cc, but did not add the new file to the src
list in rcclx/develop/projects/rccl/CMakeLists.txt. LogUtils.cc (which
IS in the list) calls into it, so librccl.so builds with two dangling
symbols:

  U meta::comms::logger::setSubSystemMask(unsigned long)
  U meta::comms::logger::isEnabledSubSystemBitwise(unsigned long)

The link does not fail because rccl links with -Wl,--allow-shlib-undefined,
so the breakage only surfaces at dlopen time. Any consumer that loads the
OSS librccl.so dies with:

  ImportError: librccl.so: undefined symbol:
  _ZN4meta5comms6logger16setSubSystemMaskEm

___

Differential Revision: D116663998