compile-time mechanism to detect unregistered CVARs for NCCL_PARAM
Summary:
# Overview
This diff introduces a compile-time mechanism to detect "unregistered" CVARs, causing a compilation to fail with an error message of the form:

```
fbcode/comms/ncclx/v2_28/src/init_nvtx.cc:19:1: error: static assertion failed due to requirement 'ncclx::isCvarRegistered("NCCL_NVTX_DISABLE")': Unregistered CVAR "NCCL_NVTX_DISABLE". Please add this CVAR to "fbcode/comms/utils/cvars/nccl_cvars.yaml", regenerate the nccl_cvars.(h|cc) files, and recompile.
   19 | NCCL_PARAM(NvtxDisable, "NVTX_DISABLE", 0);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buck-out/v2/gen/fbcode/comms/ncclx/__library_object2.28__/69ab182a567d6472/buck-headers/param.h:21:17: note: expanded from macro 'NCCL_PARAM'
   21 |   static_assert(ncclx::isCvarRegistered("NCCL_" env), "Unregistered CVAR \"NCCL_" env "\". Please add this CVAR to \"fbcode/comms/utils/cvars/nccl_cvars.yaml\", regenerate the nccl_cvars.(h|cc) files, and recompile."); \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Buck UI: https://www.internalfb.com/buck2/c0a18b6d-4da9-43ed-a00b-ca029bd24c1e
Network: Up: 481KiB  Down: 338KiB  (reSessionID-7ec94f47-39ae-471f-a156-a6878b361717)
Loading targets.   Remaining     0/1                                                                                                 1 dirs read, 26 targets declared
Analyzing targets. Remaining     0/8
Executing actions. Remaining     0/1161                                                                                              37.6s exec time total
Command: build.    Finished 64 local
Time elapsed: 7.6s
BUILD FAILED
Failed to build 'fbcode//comms/ncclx:library_object2.28 (cfg:opt-linux-x86_64-fbcode-platform010-clang19-no-san#71ea4657f8ae610e)'
```

This is achieved using a `constexpr std::array<std::string_view>` that is generated by the `extractcvars.py` script. Specifically, the script declares this array to contain the names of all registered CVARs. The `NCCL_PARAM` macro has been modified to use a `static_assert` to verify that the `env` for the associated CVAR appears within the `constexpr` array.

## Outstanding TODOs

The `NCCL_PROXY_CPUSET` CVAR should probably be a `stringlist`, which may require updating baseline.

Likewise, `NCCL_IB_HCA` is a `prefixed_stringlist` but is being parsed manually in baseline. **Supporting this CVAR required modifying baseline code. Is this acceptable?**

The `NCCL_NETWORK` CVAR uses the environment variable `NCCL_NET`. As a result, calls to `ncclGetEnv("NCCL_NETWORK");` were failing. For now, updated `extractcvars.py` to store mapping to such `std::string` CVARs (whose names and env vars differ) twice: once under name key and once under env var key. (The values are pointers, so they point to the same data.)

**Most importantly**, verify that changes do not impact 2.27 / extend beyond scope of 2.28 (as we're modifying `nccl_cvars.h` and `nccl_cvars.cc`).

Reviewed By: arttianezhu

Differential Revision: D86448745

fbshipit-source-id: 67e00563116617d708c2468269a32fa4803ce8f2