Fix with unused exception in catch (#258)
Summary:

The Ctran fails with the unused exception parameter.

Error log:
```
fbcode/comms/ctran/mapper/CtranMapperRegMem.cc:879:36: error: unused exception parameter 'e' [-Werror,-Wunused-exception-parameter]
  879 |     } catch (const std::bad_alloc& e) {
```

This diff mark them as maybe used.

Reviewed By: tanquer

Differential Revision: D91071820