Fix with unused exception in catch (#258)
Summary:
Pull Request resolved: https://github.com/meta-pytorch/torchcomms/pull/258

The Ctran fails with the unused exception parameter.

Error log:
```
fbcode/comms/ctran/mapper/CtranMapperRegMem.cc:879:36: error: unused exception parameter 'e' [-Werror,-Wunused-exception-parameter]
  879 |     } catch (const std::bad_alloc& e) {
```

This diff mark them as maybe used.

Reviewed By: tanquer

Differential Revision: D91071820

fbshipit-source-id: de753e1b96c97ab36f6e0e3270fecd0f636585b1