fix tensor wrapping using for_blob to allow external memory
Summary:
- When we access external buffer, we encountered:
```
    @                0x0 (unknown)
    @                0x0 (unknown)
W1218 15:11:30.899000 847107 site-packages/torch/multiprocessing/spawn.py:169] Terminating process 849378 via signal SIGTERM
W1218 15:11:30.900000 847107 site-packages/torch/multiprocessing/spawn.py:169] Terminating process 849380 via signal SIGTERM
W1218 15:11:30.900000 847107 site-packages/torch/multiprocessing/spawn.py:169] Terminating process 849381 via signal SIGTERM
Traceback (most recent call last):
  File "/data/users/fengtian/fbsource/genai/llama4x/projects/experimental/xinfeng/nccl_win/triton_reduce_scatter.py", line 195, in <module>
    mp.spawn(  # type: ignore
  File "/home/fengtian/.fbpkg_conda_envs/xlformers_llama4_flagship_conda-914af97/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 340, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method="spawn")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fengtian/.fbpkg_conda_envs/xlformers_llama4_flagship_conda-914af97/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 296, in start_processes
    while not context.join():
              ^^^^^^^^^^^^^^
  File "/home/fengtian/.fbpkg_conda_envs/xlformers_llama4_flagship_conda-914af97/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 215, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/fengtian/.fbpkg_conda_envs/xlformers_llama4_flagship_conda-914af97/lib/python3.12/site-packages/torch/multiprocessing/spawn.py", line 90, in _wrap
    fn(i, *args)
  File "/data/users/fengtian/fbsource/genai/llama4x/projects/experimental/xinfeng/nccl_win/triton_reduce_scatter.py", line 124, in run_tests
    ptr = win.get_tensor(i).data_ptr()
          ^^^^^^^^^^^^^^^^^
ValueError: Specified device cuda:1 does not match device of data cuda:0
```

- The root cause is that the API that we are using doesn't set target_deivce (https://www.internalfb.com/code/fbsource/[b61277c492d7854cf2e3108d31a01026db8b2e1a]/fbcode/caffe2/aten/src/ATen/ops/from_blob.h?lines=53-55), the make_tensor will query the physical ptr instead of mapped virtual memory to check whether on the same device or not (https://www.internalfb.com/code/fbsource/[b61277c492d7854cf2e3108d31a01026db8b2e1a]/fbcode/caffe2/aten/src/ATen/templates/Functions.cpp?lines=27). In remote buffer case, this will trigger the assertion since physically they are not on the same device.  In our case, we should use target_device() to bypass ATen's automatic device check when wrapping the memory pointer. This is necessary for cross-device memory access scenarios (e.g., IPC pointers where the pointer's device differs from the caller's device).  Meanwhile, memory lifetime is managed by Window (freed on tensor_deregister) No manual IPC cleanup needed.

- add UT to test tensor created on different devices

To address comments
- also remove the testing checking based on `beth0` and update the comments:
   -For tests only available on Meta's internal training clusters that have a specific network topology configuration. To determine if RDMA support is present, we check the value of DEVICE_BACKEND_NETWORK_TOPOLOGY in /etc/fbwhoami. This variable contains the RDMA network topology configuration for Meta machines. If the file does not exist or the topology is empty, it indicates that the environment is either OSS or running on inference machines without RDMA support.

Reviewed By: minsii

Differential Revision: D89500429

fbshipit-source-id: 865c8afd3fdc61ff101d3e16b3a07ce5e8266f75