Add missing FB_CUDACHECKs
Summary:
AMD build fails:

```
buck-out/v2/art/fbcode/b0db3027d13c65bd/comms/ctran/__hetero_ctran_lib_hipify_gen__/out/algos/AllReduce/AllReduceRing.cc:114:5: error: ignoring return value of type 'hipError_t' declared with 'nodiscard' attribute [-Werror,-Wunused-value]
  114 |     hipGetDevice(&cudaDev);
      |     ^~~~~~~~~~~~ ~~~~~~~~
buck-out/v2/art/fbcode/b0db3027d13c65bd/comms/ctran/__hetero_ctran_lib_hipify_gen__/out/algos/AllReduce/AllReduceRing.cc:116:5: error: ignoring return value of type 'hipError_t' declared with 'nodiscard' attribute [-Werror,-Wunused-value]
  116 |     hipDeviceGetAttribute(
      |     ^~~~~~~~~~~~~~~~~~~~~
  117 |         &smMajor, hipDeviceAttributeComputeCapabilityMajor, cudaDev);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Differential Revision: D96460398