Function definitions for utils needs to be callable from host code
Summary:
Methods in AllReduceRingCommon.cuh such as getTmpChunkId are host methods but got wrongly tagged as __device__ and hence it cannot be used in AlReduceRing.cc

Error: comms/ctran/algos/AllReduce/AllReduceRing.cc:365:20: error: no matching function for call to 'getTmpChunkId'

```
ctran/algos/AllReduce/AllReduceRingCommon.cuh:282:22 note: candidate function not viable: call to** __device__ function from __host__ function**
```

Reviewed By: liukeOoO

Differential Revision: D88429999

fbshipit-source-id: 081b5972c7e176fb73499ff08f5abf9d7c7e186a