comment out nightly cpp test workflow since it is broken
Summary:
nightly libtorch_cuda.so requires nccl 2.29 which will cause our cpp unit test has issue
```
2026-03-12T10:10:10.5166761Z /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/conda/envs/venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so: undefined reference to `ncclGetLsaMultimemDevicePointer'
2026-03-12T10:10:10.5168372Z /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/conda/envs/venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so: undefined reference to `ncclWaitSignal'
2026-03-12T10:10:10.5170009Z /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/conda/envs/venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so: undefined reference to `ncclGetPeerDevicePointer'
2026-03-12T10:10:10.5171557Z /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/conda/envs/venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so: undefined reference to `ncclPutSignal'
2026-03-12T10:10:10.5173363Z /opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /opt/conda/envs/venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so: undefined reference to `ncclSignal'
2026-03-12T10:10:10.5174377Z collect2: error: ld returned 1 exit statuslibtorch_cuda.so
```
Comment it out until nccl 2.29 rebase is finished.

Reviewed By: dsjohns2

Differential Revision: D96312466

fbshipit-source-id: 1ddce2c50debdaf453976d1affd7c5aae98d95e0